spring:
  application:
    name: shoppingApi
  h2:
    console:
      enabled: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
    contexts: local
  datasource:
    url: jdbc:h2:~/testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ''

stripe:
  key: ${STRIPE_KEY}